introduction: |-

    > Node.js idiomatic client for [Cloud Resource Manager API][product-docs].

    Google Cloud Platform provides container resources such as Organizations
    and Projects, that allow you to group and hierarchically organize other
    Cloud Platform resources. This hierarchical organization lets you easily
    manage common aspects of your resources such as access control and
    configuration settings. The [Cloud Resource Manager API](https://cloud.google.com/resource-manager/docs/)
    enables you to programmatically manage these container resources.

    ### **_IMPORTANT NOTE_**
    **Version 2.0.0 renames `@google-cloud/resource` to `@google-cloud/resource-manager` on npm.**