#!/usr/bin/env node

/**
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';

const {Storage} = require('@google-cloud/storage');
const storage = new Storage();
const NAME_REG_EXP = /^nodejs-storage-samples-[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$/;

storage
  .getBuckets()
  .then(([buckets]) => {
    let promise = Promise.resolve();

    buckets
      .filter((bucket) => NAME_REG_EXP.test(bucket.name))
      .forEach((bucket) => {
        promise = promise.then(() => {
          return bucket.deleteFiles()
            .then(() => bucket.deleteFiles(), console.error)
            .then(() => {
              console.log(`Deleting ${bucket.name}`);
              return bucket.delete();
            }, console.error)
            .catch(console.error);
        });
      });
  })
  .catch((err) => {
    console.error('ERROR:', err);
  });
