apiVersion: batch/v1
kind: Job
metadata:
  namespace: spanner-ns
  name: issue-insert-go
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: issue-insert-go
    spec:
      restartPolicy: Never
      containers:
        - name: benchmark
          image: us-central1-docker.pkg.dev/span-cloud-testing/irahul-images/issue-insert-go:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "3"
              memory: "2Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
          env:
            - name: SAMPLE_SIZE
              value: "10000"
            - name: INSERT_COUNT
              value: "1000"
            - name: INSERT_CONCURRENCY
              value: "110"
            - name: BATCH_COUNT
              value: "1"
            - name: DUPLICATE_INSERT
              value: "false"
            - name: DB_PROJECT_ID
              value: "span-cloud-testing"
            - name: DB_INSTANCE
              value: "irahul-load-test"
            - name: DB_DATABASE
              value: "db"
            - name: DB_SCHEMA
              value: "tracking"
