apiVersion: batch/v1
kind: Job
metadata:
  namespace: spanner-ns
  name: issue-insert-node-current-cluster
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: issue-insert-node-current-cluster
    spec:
      restartPolicy: Never
      containers:
        - name: benchmark
          image: us-central1-docker.pkg.dev/span-cloud-testing/gargsurbhi-images/issue-insert-node-cluster:current
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "3"
              memory: "3Gi"
            limits:
              cpu: "3"
              memory: "3Gi"
          env:
            - name: CLUSTER_WORKERS
              value: "3"
            - name: SAMPLE_SIZE
              value: "10000"
            - name: INSERT_COUNT
              value: "1000"
            - name: INSERT_CONCURRENCY
              value: "24"
            - name: BATCH_COUNT
              value: "1"
            - name: DUPLICATE_INSERT
              value: "false"
            - name: VERBOSE_BATCH_LOGS
              value: "true"
            - name: DB_PROJECT_ID
              value: "span-cloud-testing"
            - name: DB_INSTANCE
              value: "gargsurbhi-testing1"
            - name: DB_DATABASE
              value: "jack_henry_db"
            - name: DB_SCHEMA
              value: "tracking"
