introduction: |-
  > Node.js idiomatic client for [Kubernetes Engine][product-docs] cluster management.

  [Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/) is used for
  building and managing container based applications, powered by the open source Kubernetes technology.
body: |-

  ## Relationship to Kubernetes

  `@google-cloud/container` provides a high level API for creating and managing
  [Google Kubernetes Engine](https://cloud.google.com/gke) clusters on Google Cloud.

  To run commands against the clusters created, you will need to use the
  [Kubernetes API](https://kubernetes.io/docs/reference/using-api/api-overview/)
  (and the associated kubectl command-line interface).
