allowedCopyrightHolders:
  - 'Google LLC'
allowedLicenses:
  - 'Apache-2.0'
  - 'MIT'
  - 'BSD-3'
sourceFileExtensions:
  - 'ts'
  - 'js'
  - 'java'
ignoreFiles:
  - "packages/*/webpack.config.js"
  - "packages/*/__snapshots__/**/*.js"
  - "packages/typeless-sample-bot/test/fixtures/**/*.ts"
  - "packages/typeless-sample-bot/test/fixtures/**/*.js"
