name: pull-request

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILD_SUMMARY: "false"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  DOCKER_BUILDKIT: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##################
  # VALIDATE FUNCTIONS
  ##################
  validate-logging-winston:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    env:
      TARGET_PATH: "handwritten/logging-winston"
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            src:
              - ${{env.TARGET_PATH}}/**

      - if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: ${{ env.TARGET_PATH }}/package-lock.json

      - if: steps.changes.outputs.src == 'true'
        name: npm ci
        run: npm ci
        working-directory: ${{ env.TARGET_PATH }}/

      - if: steps.changes.outputs.src == 'true'
        name: Typecheck
        run: npm run compile
        working-directory: ${{ env.TARGET_PATH }}/

      - if: steps.changes.outputs.src == 'true'
        name: Test
        run: npm run test
        env:
          CI: true
        working-directory: ${{ env.TARGET_PATH }}/
