packages:
  - 'core/common'
  - 'core/paginator'
  - 'core/precise-date'
  - 'core/projectify'
  - 'core/promisify'
  - 'core/packages/*'
  - 'core/dev-packages/*'
  - 'packages/*'
  - 'handwritten/*'
  - 'containers/*'
  - '!**/fixtures/**'
  - '!**/test-fixtures/**'
  - '!**/baselines/**'
  - '!**/baselines-esm/**'
  - '!**/templates/**'
