// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

export {AlertPolicyServiceClient} from './alert_policy_service_client';
export {GroupServiceClient} from './group_service_client';
export {MetricServiceClient} from './metric_service_client';
export {NotificationChannelServiceClient} from './notification_channel_service_client';
export {QueryServiceClient} from './query_service_client';
export {ServiceMonitoringServiceClient} from './service_monitoring_service_client';
export {SnoozeServiceClient} from './snooze_service_client';
export {UptimeCheckServiceClient} from './uptime_check_service_client';
