// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import type * as gax from 'google-gax';
import type {
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
} from 'google-gax';

import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');

/**
 * Client JSON configuration object, loaded from
 * `src/v1/css_product_inputs_service_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './css_product_inputs_service_client_config.json';
const version = require('../../../package.json').version;

/**
 *  Service to use CssProductInput resource.
 *  This service helps to insert/update/delete CSS Products.
 * @class
 * @memberof v1
 */
export class CssProductInputsServiceClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _providedCustomServicePath: boolean;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  private _universeDomain: string;
  private _servicePath: string;
  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  warn: (code: string, message: string, warnType?: string) => void;
  innerApiCalls: {[name: string]: Function};
  pathTemplates: {[name: string]: gax.PathTemplate};
  cssProductInputsServiceStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of CssProductInputsServiceClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP/1.1 REST mode.
   *     For more information, please check the
   *     {@link https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#http11-rest-api-mode documentation}.
   * @param {gax} [gaxInstance]: loaded instance of `google-gax`. Useful if you
   *     need to avoid loading the default gRPC version and want to use the fallback
   *     HTTP implementation. Load only fallback version and pass it to the constructor:
   *     ```
   *     const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC
   *     const client = new CssProductInputsServiceClient({fallback: true}, gax);
   *     ```
   */
  constructor(
    opts?: ClientOptions,
    gaxInstance?: typeof gax | typeof gax.fallback
  ) {
    // Ensure that options include all the required fields.
    const staticMembers = this
      .constructor as typeof CssProductInputsServiceClient;
    if (
      opts?.universe_domain &&
      opts?.universeDomain &&
      opts?.universe_domain !== opts?.universeDomain
    ) {
      throw new Error(
        'Please set either universe_domain or universeDomain, but not both.'
      );
    }
    const universeDomainEnvVar =
      typeof process === 'object' && typeof process.env === 'object'
        ? process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN']
        : undefined;
    this._universeDomain =
      opts?.universeDomain ??
      opts?.universe_domain ??
      universeDomainEnvVar ??
      'googleapis.com';
    this._servicePath = 'css.' + this._universeDomain;
    const servicePath =
      opts?.servicePath || opts?.apiEndpoint || this._servicePath;
    this._providedCustomServicePath = !!(
      opts?.servicePath || opts?.apiEndpoint
    );
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback =
      opts?.fallback ??
      (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // Request numeric enum values if REST transport is used.
    opts.numericEnums = true;

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== this._servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Load google-gax module synchronously if needed
    if (!gaxInstance) {
      gaxInstance = require('google-gax') as typeof gax;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gaxInstance.fallback : gaxInstance;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    // Set useJWTAccessWithScope on the auth object.
    this.auth.useJWTAccessWithScope = true;

    // Set defaultServicePath on the auth object.
    this.auth.defaultServicePath = this._servicePath;

    // Set the default scopes in auth client if needed.
    if (servicePath === this._servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }

    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process === 'object' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    } else {
      clientHeader.push(`rest/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      accountPathTemplate: new this._gaxModule.PathTemplate(
        'accounts/{account}'
      ),
      accountLabelPathTemplate: new this._gaxModule.PathTemplate(
        'accounts/{account}/labels/{label}'
      ),
      cssProductPathTemplate: new this._gaxModule.PathTemplate(
        'accounts/{account}/cssProducts/{css_product}'
      ),
      cssProductInputPathTemplate: new this._gaxModule.PathTemplate(
        'accounts/{account}/cssProductInputs/{css_product_input}'
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.shopping.css.v1.CssProductInputsService',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')}
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};

    // Add a warn function to the client constructor so it can be easily tested.
    this.warn = this._gaxModule.warn;
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.cssProductInputsServiceStub) {
      return this.cssProductInputsServiceStub;
    }

    // Put together the "service stub" for
    // google.shopping.css.v1.CssProductInputsService.
    this.cssProductInputsServiceStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.shopping.css.v1.CssProductInputsService'
          )
        : // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.shopping.css.v1.CssProductInputsService,
      this._opts,
      this._providedCustomServicePath
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const cssProductInputsServiceStubMethods = [
      'insertCssProductInput',
      'updateCssProductInput',
      'deleteCssProductInput',
    ];
    for (const methodName of cssProductInputsServiceStubMethods) {
      const callPromise = this.cssProductInputsServiceStub.then(
        stub =>
          (...args: Array<{}>) => {
            if (this._terminated) {
              return Promise.reject('The client has already been closed.');
            }
            const func = stub[methodName];
            return func.apply(stub, args);
          },
        (err: Error | null | undefined) => () => {
          throw err;
        }
      );

      const descriptor = undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor,
        this._opts.fallback
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.cssProductInputsServiceStub;
  }

  /**
   * The DNS address for this API service.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static servicePath is deprecated, please use the instance method instead.',
        'DeprecationWarning'
      );
    }
    return 'css.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static apiEndpoint is deprecated, please use the instance method instead.',
        'DeprecationWarning'
      );
    }
    return 'css.googleapis.com';
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  get apiEndpoint() {
    return this._servicePath;
  }

  get universeDomain() {
    return this._universeDomain;
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return ['https://www.googleapis.com/auth/content'];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  /**
   * Uploads a CssProductInput to your CSS Center account. If an
   * input with the same contentLanguage, identity, feedLabel and feedId already
   * exists, this method replaces that entry.
   *
   * After inserting, updating, or deleting a CSS Product input, it may
   * take several minutes before the processed CSS Product can be retrieved.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. The account where this CSS Product will be inserted.
   *   Format: accounts/{account}
   * @param {google.shopping.css.v1.CssProductInput} request.cssProductInput
   *   Required. The CSS Product Input to insert.
   * @param {number} [request.feedId]
   *   Optional. DEPRECATED. Feed id is not required for CSS Products.
   *   The primary or supplemental feed id. If CSS Product already exists and
   *   feed id provided is different, then the CSS Product will be moved to a
   *   new feed.
   *   Note: For now, CSSs do not need to provide feed ids as we create
   *   feeds on the fly.
   *   We do not have supplemental feed support for CSS Products yet.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.shopping.css.v1.CssProductInput|CssProductInput}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/css_product_inputs_service.insert_css_product_input.js</caption>
   * region_tag:css_v1_generated_CssProductInputsService_InsertCssProductInput_async
   */
  insertCssProductInput(
    request?: protos.google.shopping.css.v1.IInsertCssProductInputRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.shopping.css.v1.ICssProductInput,
      protos.google.shopping.css.v1.IInsertCssProductInputRequest | undefined,
      {} | undefined,
    ]
  >;
  insertCssProductInput(
    request: protos.google.shopping.css.v1.IInsertCssProductInputRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IInsertCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  insertCssProductInput(
    request: protos.google.shopping.css.v1.IInsertCssProductInputRequest,
    callback: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IInsertCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  insertCssProductInput(
    request?: protos.google.shopping.css.v1.IInsertCssProductInputRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.shopping.css.v1.ICssProductInput,
          | protos.google.shopping.css.v1.IInsertCssProductInputRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IInsertCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.shopping.css.v1.ICssProductInput,
      protos.google.shopping.css.v1.IInsertCssProductInputRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        parent: request.parent ?? '',
      });
    this.initialize();
    return this.innerApiCalls.insertCssProductInput(request, options, callback);
  }
  /**
   * Updates the existing Css Product input in your CSS Center account.
   *
   * After inserting, updating, or deleting a CSS Product input, it may take
   * several minutes before the processed Css Product can be retrieved.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {google.shopping.css.v1.CssProductInput} request.cssProductInput
   *   Required. The CSS product input resource to update. Information you submit
   *   will be applied to the processed CSS product as well.
   * @param {google.protobuf.FieldMask} request.updateMask
   *   The list of CSS product attributes to be updated.
   *
   *   If the update mask is omitted, then it is treated as implied field mask
   *   equivalent to all fields that are populated (have a non-empty value).
   *
   *   Attributes specified in the update mask without a value specified in the
   *   body will be deleted from the CSS product.
   *
   *   Update mask can only be specified for top level fields in
   *   attributes and custom attributes.
   *
   *   To specify the update mask for custom attributes you need to add the
   *   `custom_attribute.` prefix.
   *
   *   Providing special "*" value for full CSS product replacement is not
   *   supported.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.shopping.css.v1.CssProductInput|CssProductInput}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/css_product_inputs_service.update_css_product_input.js</caption>
   * region_tag:css_v1_generated_CssProductInputsService_UpdateCssProductInput_async
   */
  updateCssProductInput(
    request?: protos.google.shopping.css.v1.IUpdateCssProductInputRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.shopping.css.v1.ICssProductInput,
      protos.google.shopping.css.v1.IUpdateCssProductInputRequest | undefined,
      {} | undefined,
    ]
  >;
  updateCssProductInput(
    request: protos.google.shopping.css.v1.IUpdateCssProductInputRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IUpdateCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  updateCssProductInput(
    request: protos.google.shopping.css.v1.IUpdateCssProductInputRequest,
    callback: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IUpdateCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  updateCssProductInput(
    request?: protos.google.shopping.css.v1.IUpdateCssProductInputRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.shopping.css.v1.ICssProductInput,
          | protos.google.shopping.css.v1.IUpdateCssProductInputRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.shopping.css.v1.ICssProductInput,
      | protos.google.shopping.css.v1.IUpdateCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.shopping.css.v1.ICssProductInput,
      protos.google.shopping.css.v1.IUpdateCssProductInputRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        'css_product_input.name': request.cssProductInput!.name ?? '',
      });
    this.initialize();
    return this.innerApiCalls.updateCssProductInput(request, options, callback);
  }
  /**
   * Deletes a CSS Product input from your CSS Center account.
   *
   * After a delete it may take several minutes until the input is no longer
   * available.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the CSS product input resource to delete.
   *   Format: accounts/{account}/cssProductInputs/{css_product_input}
   * @param {number} request.supplementalFeedId
   *   The Content API Supplemental Feed ID.
   *   The field must not be set if the action applies to a primary feed.
   *   If the field is set, then product action applies to a supplemental feed
   *   instead of primary Content API feed.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.protobuf.Empty|Empty}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/css_product_inputs_service.delete_css_product_input.js</caption>
   * region_tag:css_v1_generated_CssProductInputsService_DeleteCssProductInput_async
   */
  deleteCssProductInput(
    request?: protos.google.shopping.css.v1.IDeleteCssProductInputRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.protobuf.IEmpty,
      protos.google.shopping.css.v1.IDeleteCssProductInputRequest | undefined,
      {} | undefined,
    ]
  >;
  deleteCssProductInput(
    request: protos.google.shopping.css.v1.IDeleteCssProductInputRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.protobuf.IEmpty,
      | protos.google.shopping.css.v1.IDeleteCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  deleteCssProductInput(
    request: protos.google.shopping.css.v1.IDeleteCssProductInputRequest,
    callback: Callback<
      protos.google.protobuf.IEmpty,
      | protos.google.shopping.css.v1.IDeleteCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  deleteCssProductInput(
    request?: protos.google.shopping.css.v1.IDeleteCssProductInputRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.protobuf.IEmpty,
          | protos.google.shopping.css.v1.IDeleteCssProductInputRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.protobuf.IEmpty,
      | protos.google.shopping.css.v1.IDeleteCssProductInputRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.protobuf.IEmpty,
      protos.google.shopping.css.v1.IDeleteCssProductInputRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize();
    return this.innerApiCalls.deleteCssProductInput(request, options, callback);
  }

  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified account resource name string.
   *
   * @param {string} account
   * @returns {string} Resource name string.
   */
  accountPath(account: string) {
    return this.pathTemplates.accountPathTemplate.render({
      account: account,
    });
  }

  /**
   * Parse the account from Account resource.
   *
   * @param {string} accountName
   *   A fully-qualified path representing Account resource.
   * @returns {string} A string representing the account.
   */
  matchAccountFromAccountName(accountName: string) {
    return this.pathTemplates.accountPathTemplate.match(accountName).account;
  }

  /**
   * Return a fully-qualified accountLabel resource name string.
   *
   * @param {string} account
   * @param {string} label
   * @returns {string} Resource name string.
   */
  accountLabelPath(account: string, label: string) {
    return this.pathTemplates.accountLabelPathTemplate.render({
      account: account,
      label: label,
    });
  }

  /**
   * Parse the account from AccountLabel resource.
   *
   * @param {string} accountLabelName
   *   A fully-qualified path representing AccountLabel resource.
   * @returns {string} A string representing the account.
   */
  matchAccountFromAccountLabelName(accountLabelName: string) {
    return this.pathTemplates.accountLabelPathTemplate.match(accountLabelName)
      .account;
  }

  /**
   * Parse the label from AccountLabel resource.
   *
   * @param {string} accountLabelName
   *   A fully-qualified path representing AccountLabel resource.
   * @returns {string} A string representing the label.
   */
  matchLabelFromAccountLabelName(accountLabelName: string) {
    return this.pathTemplates.accountLabelPathTemplate.match(accountLabelName)
      .label;
  }

  /**
   * Return a fully-qualified cssProduct resource name string.
   *
   * @param {string} account
   * @param {string} css_product
   * @returns {string} Resource name string.
   */
  cssProductPath(account: string, cssProduct: string) {
    return this.pathTemplates.cssProductPathTemplate.render({
      account: account,
      css_product: cssProduct,
    });
  }

  /**
   * Parse the account from CssProduct resource.
   *
   * @param {string} cssProductName
   *   A fully-qualified path representing CssProduct resource.
   * @returns {string} A string representing the account.
   */
  matchAccountFromCssProductName(cssProductName: string) {
    return this.pathTemplates.cssProductPathTemplate.match(cssProductName)
      .account;
  }

  /**
   * Parse the css_product from CssProduct resource.
   *
   * @param {string} cssProductName
   *   A fully-qualified path representing CssProduct resource.
   * @returns {string} A string representing the css_product.
   */
  matchCssProductFromCssProductName(cssProductName: string) {
    return this.pathTemplates.cssProductPathTemplate.match(cssProductName)
      .css_product;
  }

  /**
   * Return a fully-qualified cssProductInput resource name string.
   *
   * @param {string} account
   * @param {string} css_product_input
   * @returns {string} Resource name string.
   */
  cssProductInputPath(account: string, cssProductInput: string) {
    return this.pathTemplates.cssProductInputPathTemplate.render({
      account: account,
      css_product_input: cssProductInput,
    });
  }

  /**
   * Parse the account from CssProductInput resource.
   *
   * @param {string} cssProductInputName
   *   A fully-qualified path representing CssProductInput resource.
   * @returns {string} A string representing the account.
   */
  matchAccountFromCssProductInputName(cssProductInputName: string) {
    return this.pathTemplates.cssProductInputPathTemplate.match(
      cssProductInputName
    ).account;
  }

  /**
   * Parse the css_product_input from CssProductInput resource.
   *
   * @param {string} cssProductInputName
   *   A fully-qualified path representing CssProductInput resource.
   * @returns {string} A string representing the css_product_input.
   */
  matchCssProductInputFromCssProductInputName(cssProductInputName: string) {
    return this.pathTemplates.cssProductInputPathTemplate.match(
      cssProductInputName
    ).css_product_input;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    if (this.cssProductInputsServiceStub && !this._terminated) {
      return this.cssProductInputsServiceStub.then(stub => {
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
}
