introduction: |-
    Google Cloud AI Platform is an integrated suite of machine learning tools
    and services for building and using ML models with AutoML or custom code.
    It offers both novices and experts the best workbench for the entire
    machine learning development lifecycle.