// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import type * as gax from 'google-gax';
import type {
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
  LocationsClient,
  LocationProtos,
} from 'google-gax';

import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');
import {loggingUtils as logging} from 'google-gax';

/**
 * Client JSON configuration object, loaded from
 * `src/v1/api_hub_plugin_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './api_hub_plugin_client_config.json';
const version = require('../../../package.json').version;

/**
 *  This service is used for managing plugins inside the API Hub.
 * @class
 * @memberof v1
 */
export class ApiHubPluginClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _providedCustomServicePath: boolean;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  private _universeDomain: string;
  private _servicePath: string;
  private _log = logging.log('apihub');

  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  warn: (code: string, message: string, warnType?: string) => void;
  innerApiCalls: {[name: string]: Function};
  locationsClient: LocationsClient;
  pathTemplates: {[name: string]: gax.PathTemplate};
  apiHubPluginStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of ApiHubPluginClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://cloud.google.com/docs/authentication/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP/1.1 REST mode.
   *     For more information, please check the
   *     {@link https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#http11-rest-api-mode documentation}.
   * @param {gax} [gaxInstance]: loaded instance of `google-gax`. Useful if you
   *     need to avoid loading the default gRPC version and want to use the fallback
   *     HTTP implementation. Load only fallback version and pass it to the constructor:
   *     ```
   *     const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC
   *     const client = new ApiHubPluginClient({fallback: true}, gax);
   *     ```
   */
  constructor(
    opts?: ClientOptions,
    gaxInstance?: typeof gax | typeof gax.fallback
  ) {
    // Ensure that options include all the required fields.
    const staticMembers = this.constructor as typeof ApiHubPluginClient;
    if (
      opts?.universe_domain &&
      opts?.universeDomain &&
      opts?.universe_domain !== opts?.universeDomain
    ) {
      throw new Error(
        'Please set either universe_domain or universeDomain, but not both.'
      );
    }
    const universeDomainEnvVar =
      typeof process === 'object' && typeof process.env === 'object'
        ? process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN']
        : undefined;
    this._universeDomain =
      opts?.universeDomain ??
      opts?.universe_domain ??
      universeDomainEnvVar ??
      'googleapis.com';
    this._servicePath = 'apihub.' + this._universeDomain;
    const servicePath =
      opts?.servicePath || opts?.apiEndpoint || this._servicePath;
    this._providedCustomServicePath = !!(
      opts?.servicePath || opts?.apiEndpoint
    );
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    // Implicitly enable HTTP transport for the APIs that use REST as transport (e.g. Google Cloud Compute).
    if (!opts) {
      opts = {fallback: true};
    } else {
      opts.fallback = opts.fallback ?? true;
    }
    const fallback =
      opts?.fallback ??
      (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // Request numeric enum values if REST transport is used.
    opts.numericEnums = true;

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== this._servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Load google-gax module synchronously if needed
    if (!gaxInstance) {
      gaxInstance = require('google-gax') as typeof gax;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gaxInstance.fallback : gaxInstance;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    // Set useJWTAccessWithScope on the auth object.
    this.auth.useJWTAccessWithScope = true;

    // Set defaultServicePath on the auth object.
    this.auth.defaultServicePath = this._servicePath;

    // Set the default scopes in auth client if needed.
    if (servicePath === this._servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }
    this.locationsClient = new this._gaxModule.LocationsClient(
      this._gaxGrpc,
      opts
    );

    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process === 'object' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    } else {
      clientHeader.push(`rest/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      apiPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apis/{api}'
      ),
      apiHubInstancePathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apiHubInstances/{api_hub_instance}'
      ),
      apiOperationPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apis/{api}/versions/{version}/operations/{operation}'
      ),
      attributePathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/attributes/{attribute}'
      ),
      definitionPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apis/{api}/versions/{version}/definitions/{definition}'
      ),
      dependencyPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/dependencies/{dependency}'
      ),
      deploymentPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/deployments/{deployment}'
      ),
      externalApiPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/externalApis/{external_api}'
      ),
      hostProjectRegistrationPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/hostProjectRegistrations/{host_project_registration}'
      ),
      pluginPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/plugins/{plugin}'
      ),
      runtimeProjectAttachmentPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/runtimeProjectAttachments/{runtime_project_attachment}'
      ),
      specPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apis/{api}/versions/{version}/specs/{spec}'
      ),
      styleGuidePathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/plugins/{plugin}/styleGuide'
      ),
      versionPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/apis/{api}/versions/{version}'
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.cloud.apihub.v1.ApiHubPlugin',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')}
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};

    // Add a warn function to the client constructor so it can be easily tested.
    this.warn = this._gaxModule.warn;
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.apiHubPluginStub) {
      return this.apiHubPluginStub;
    }

    // Put together the "service stub" for
    // google.cloud.apihub.v1.ApiHubPlugin.
    this.apiHubPluginStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.cloud.apihub.v1.ApiHubPlugin'
          )
        : // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.cloud.apihub.v1.ApiHubPlugin,
      this._opts,
      this._providedCustomServicePath
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const apiHubPluginStubMethods = [
      'getPlugin',
      'enablePlugin',
      'disablePlugin',
    ];
    for (const methodName of apiHubPluginStubMethods) {
      const callPromise = this.apiHubPluginStub.then(
        stub =>
          (...args: Array<{}>) => {
            if (this._terminated) {
              return Promise.reject('The client has already been closed.');
            }
            const func = stub[methodName];
            return func.apply(stub, args);
          },
        (err: Error | null | undefined) => () => {
          throw err;
        }
      );

      const descriptor = undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor,
        this._opts.fallback
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.apiHubPluginStub;
  }

  /**
   * The DNS address for this API service.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static servicePath is deprecated, please use the instance method instead.',
        'DeprecationWarning'
      );
    }
    return 'apihub.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static apiEndpoint is deprecated, please use the instance method instead.',
        'DeprecationWarning'
      );
    }
    return 'apihub.googleapis.com';
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  get apiEndpoint() {
    return this._servicePath;
  }

  get universeDomain() {
    return this._universeDomain;
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return ['https://www.googleapis.com/auth/cloud-platform'];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  /**
   * Get details about an API Hub plugin.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the plugin to retrieve.
   *   Format: `projects/{project}/locations/{location}/plugins/{plugin}`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.apihub.v1.Plugin|Plugin}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/api_hub_plugin.get_plugin.js</caption>
   * region_tag:apihub_v1_generated_ApiHubPlugin_GetPlugin_async
   */
  getPlugin(
    request?: protos.google.cloud.apihub.v1.IGetPluginRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IGetPluginRequest | undefined,
      {} | undefined,
    ]
  >;
  getPlugin(
    request: protos.google.cloud.apihub.v1.IGetPluginRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IGetPluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  getPlugin(
    request: protos.google.cloud.apihub.v1.IGetPluginRequest,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IGetPluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  getPlugin(
    request?: protos.google.cloud.apihub.v1.IGetPluginRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IGetPluginRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IGetPluginRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IGetPluginRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('getPlugin request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IGetPluginRequest | null | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('getPlugin response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .getPlugin(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IGetPluginRequest | undefined,
          {} | undefined,
        ]) => {
          this._log.info('getPlugin response %j', response);
          return [response, options, rawResponse];
        }
      );
  }
  /**
   * Enables a plugin.
   * The `state` of the plugin after enabling is `ENABLED`
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the plugin to enable.
   *   Format: `projects/{project}/locations/{location}/plugins/{plugin}`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.apihub.v1.Plugin|Plugin}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/api_hub_plugin.enable_plugin.js</caption>
   * region_tag:apihub_v1_generated_ApiHubPlugin_EnablePlugin_async
   */
  enablePlugin(
    request?: protos.google.cloud.apihub.v1.IEnablePluginRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IEnablePluginRequest | undefined,
      {} | undefined,
    ]
  >;
  enablePlugin(
    request: protos.google.cloud.apihub.v1.IEnablePluginRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IEnablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  enablePlugin(
    request: protos.google.cloud.apihub.v1.IEnablePluginRequest,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IEnablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  enablePlugin(
    request?: protos.google.cloud.apihub.v1.IEnablePluginRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IEnablePluginRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IEnablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IEnablePluginRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('enablePlugin request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IEnablePluginRequest | null | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('enablePlugin response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .enablePlugin(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IEnablePluginRequest | undefined,
          {} | undefined,
        ]) => {
          this._log.info('enablePlugin response %j', response);
          return [response, options, rawResponse];
        }
      );
  }
  /**
   * Disables a plugin.
   * The `state` of the plugin after disabling is `DISABLED`
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the plugin to disable.
   *   Format: `projects/{project}/locations/{location}/plugins/{plugin}`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.apihub.v1.Plugin|Plugin}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1/api_hub_plugin.disable_plugin.js</caption>
   * region_tag:apihub_v1_generated_ApiHubPlugin_DisablePlugin_async
   */
  disablePlugin(
    request?: protos.google.cloud.apihub.v1.IDisablePluginRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IDisablePluginRequest | undefined,
      {} | undefined,
    ]
  >;
  disablePlugin(
    request: protos.google.cloud.apihub.v1.IDisablePluginRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IDisablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  disablePlugin(
    request: protos.google.cloud.apihub.v1.IDisablePluginRequest,
    callback: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IDisablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  disablePlugin(
    request?: protos.google.cloud.apihub.v1.IDisablePluginRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          | protos.google.cloud.apihub.v1.IDisablePluginRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IDisablePluginRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.apihub.v1.IPlugin,
      protos.google.cloud.apihub.v1.IDisablePluginRequest | undefined,
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('disablePlugin request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.apihub.v1.IPlugin,
          | protos.google.cloud.apihub.v1.IDisablePluginRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('disablePlugin response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .disablePlugin(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.apihub.v1.IPlugin,
          protos.google.cloud.apihub.v1.IDisablePluginRequest | undefined,
          {} | undefined,
        ]) => {
          this._log.info('disablePlugin response %j', response);
          return [response, options, rawResponse];
        }
      );
  }

  /**
   * Gets information about a location.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Resource name for the location.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html | CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link google.cloud.location.Location | Location}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const [response] = await client.getLocation(request);
   * ```
   */
  getLocation(
    request: LocationProtos.google.cloud.location.IGetLocationRequest,
    options?:
      | gax.CallOptions
      | Callback<
          LocationProtos.google.cloud.location.ILocation,
          | LocationProtos.google.cloud.location.IGetLocationRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      LocationProtos.google.cloud.location.ILocation,
      | LocationProtos.google.cloud.location.IGetLocationRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.getLocation(request, options, callback);
  }

  /**
   * Lists information about the supported locations for this service. Returns an iterable object.
   *
   * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   The resource that owns the locations collection, if applicable.
   * @param {string} request.filter
   *   The standard list filter.
   * @param {number} request.pageSize
   *   The standard list page size.
   * @param {string} request.pageToken
   *   The standard list page token.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Object}
   *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
   *   When you iterate the returned iterable, each element will be an object representing
   *   {@link google.cloud.location.Location | Location}. The API will be called under the hood as needed, once per the page,
   *   so you can stop the iteration when you don't need more results.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const iterable = client.listLocationsAsync(request);
   * for await (const response of iterable) {
   *   // process response
   * }
   * ```
   */
  listLocationsAsync(
    request: LocationProtos.google.cloud.location.IListLocationsRequest,
    options?: CallOptions
  ): AsyncIterable<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.listLocationsAsync(request, options);
  }

  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified api resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api
   * @returns {string} Resource name string.
   */
  apiPath(project: string, location: string, api: string) {
    return this.pathTemplates.apiPathTemplate.render({
      project: project,
      location: location,
      api: api,
    });
  }

  /**
   * Parse the project from Api resource.
   *
   * @param {string} apiName
   *   A fully-qualified path representing Api resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromApiName(apiName: string) {
    return this.pathTemplates.apiPathTemplate.match(apiName).project;
  }

  /**
   * Parse the location from Api resource.
   *
   * @param {string} apiName
   *   A fully-qualified path representing Api resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromApiName(apiName: string) {
    return this.pathTemplates.apiPathTemplate.match(apiName).location;
  }

  /**
   * Parse the api from Api resource.
   *
   * @param {string} apiName
   *   A fully-qualified path representing Api resource.
   * @returns {string} A string representing the api.
   */
  matchApiFromApiName(apiName: string) {
    return this.pathTemplates.apiPathTemplate.match(apiName).api;
  }

  /**
   * Return a fully-qualified apiHubInstance resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api_hub_instance
   * @returns {string} Resource name string.
   */
  apiHubInstancePath(
    project: string,
    location: string,
    apiHubInstance: string
  ) {
    return this.pathTemplates.apiHubInstancePathTemplate.render({
      project: project,
      location: location,
      api_hub_instance: apiHubInstance,
    });
  }

  /**
   * Parse the project from ApiHubInstance resource.
   *
   * @param {string} apiHubInstanceName
   *   A fully-qualified path representing ApiHubInstance resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromApiHubInstanceName(apiHubInstanceName: string) {
    return this.pathTemplates.apiHubInstancePathTemplate.match(
      apiHubInstanceName
    ).project;
  }

  /**
   * Parse the location from ApiHubInstance resource.
   *
   * @param {string} apiHubInstanceName
   *   A fully-qualified path representing ApiHubInstance resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromApiHubInstanceName(apiHubInstanceName: string) {
    return this.pathTemplates.apiHubInstancePathTemplate.match(
      apiHubInstanceName
    ).location;
  }

  /**
   * Parse the api_hub_instance from ApiHubInstance resource.
   *
   * @param {string} apiHubInstanceName
   *   A fully-qualified path representing ApiHubInstance resource.
   * @returns {string} A string representing the api_hub_instance.
   */
  matchApiHubInstanceFromApiHubInstanceName(apiHubInstanceName: string) {
    return this.pathTemplates.apiHubInstancePathTemplate.match(
      apiHubInstanceName
    ).api_hub_instance;
  }

  /**
   * Return a fully-qualified apiOperation resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api
   * @param {string} version
   * @param {string} operation
   * @returns {string} Resource name string.
   */
  apiOperationPath(
    project: string,
    location: string,
    api: string,
    version: string,
    operation: string
  ) {
    return this.pathTemplates.apiOperationPathTemplate.render({
      project: project,
      location: location,
      api: api,
      version: version,
      operation: operation,
    });
  }

  /**
   * Parse the project from ApiOperation resource.
   *
   * @param {string} apiOperationName
   *   A fully-qualified path representing ApiOperation resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromApiOperationName(apiOperationName: string) {
    return this.pathTemplates.apiOperationPathTemplate.match(apiOperationName)
      .project;
  }

  /**
   * Parse the location from ApiOperation resource.
   *
   * @param {string} apiOperationName
   *   A fully-qualified path representing ApiOperation resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromApiOperationName(apiOperationName: string) {
    return this.pathTemplates.apiOperationPathTemplate.match(apiOperationName)
      .location;
  }

  /**
   * Parse the api from ApiOperation resource.
   *
   * @param {string} apiOperationName
   *   A fully-qualified path representing ApiOperation resource.
   * @returns {string} A string representing the api.
   */
  matchApiFromApiOperationName(apiOperationName: string) {
    return this.pathTemplates.apiOperationPathTemplate.match(apiOperationName)
      .api;
  }

  /**
   * Parse the version from ApiOperation resource.
   *
   * @param {string} apiOperationName
   *   A fully-qualified path representing ApiOperation resource.
   * @returns {string} A string representing the version.
   */
  matchVersionFromApiOperationName(apiOperationName: string) {
    return this.pathTemplates.apiOperationPathTemplate.match(apiOperationName)
      .version;
  }

  /**
   * Parse the operation from ApiOperation resource.
   *
   * @param {string} apiOperationName
   *   A fully-qualified path representing ApiOperation resource.
   * @returns {string} A string representing the operation.
   */
  matchOperationFromApiOperationName(apiOperationName: string) {
    return this.pathTemplates.apiOperationPathTemplate.match(apiOperationName)
      .operation;
  }

  /**
   * Return a fully-qualified attribute resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} attribute
   * @returns {string} Resource name string.
   */
  attributePath(project: string, location: string, attribute: string) {
    return this.pathTemplates.attributePathTemplate.render({
      project: project,
      location: location,
      attribute: attribute,
    });
  }

  /**
   * Parse the project from Attribute resource.
   *
   * @param {string} attributeName
   *   A fully-qualified path representing Attribute resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromAttributeName(attributeName: string) {
    return this.pathTemplates.attributePathTemplate.match(attributeName)
      .project;
  }

  /**
   * Parse the location from Attribute resource.
   *
   * @param {string} attributeName
   *   A fully-qualified path representing Attribute resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromAttributeName(attributeName: string) {
    return this.pathTemplates.attributePathTemplate.match(attributeName)
      .location;
  }

  /**
   * Parse the attribute from Attribute resource.
   *
   * @param {string} attributeName
   *   A fully-qualified path representing Attribute resource.
   * @returns {string} A string representing the attribute.
   */
  matchAttributeFromAttributeName(attributeName: string) {
    return this.pathTemplates.attributePathTemplate.match(attributeName)
      .attribute;
  }

  /**
   * Return a fully-qualified definition resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api
   * @param {string} version
   * @param {string} definition
   * @returns {string} Resource name string.
   */
  definitionPath(
    project: string,
    location: string,
    api: string,
    version: string,
    definition: string
  ) {
    return this.pathTemplates.definitionPathTemplate.render({
      project: project,
      location: location,
      api: api,
      version: version,
      definition: definition,
    });
  }

  /**
   * Parse the project from Definition resource.
   *
   * @param {string} definitionName
   *   A fully-qualified path representing Definition resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromDefinitionName(definitionName: string) {
    return this.pathTemplates.definitionPathTemplate.match(definitionName)
      .project;
  }

  /**
   * Parse the location from Definition resource.
   *
   * @param {string} definitionName
   *   A fully-qualified path representing Definition resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromDefinitionName(definitionName: string) {
    return this.pathTemplates.definitionPathTemplate.match(definitionName)
      .location;
  }

  /**
   * Parse the api from Definition resource.
   *
   * @param {string} definitionName
   *   A fully-qualified path representing Definition resource.
   * @returns {string} A string representing the api.
   */
  matchApiFromDefinitionName(definitionName: string) {
    return this.pathTemplates.definitionPathTemplate.match(definitionName).api;
  }

  /**
   * Parse the version from Definition resource.
   *
   * @param {string} definitionName
   *   A fully-qualified path representing Definition resource.
   * @returns {string} A string representing the version.
   */
  matchVersionFromDefinitionName(definitionName: string) {
    return this.pathTemplates.definitionPathTemplate.match(definitionName)
      .version;
  }

  /**
   * Parse the definition from Definition resource.
   *
   * @param {string} definitionName
   *   A fully-qualified path representing Definition resource.
   * @returns {string} A string representing the definition.
   */
  matchDefinitionFromDefinitionName(definitionName: string) {
    return this.pathTemplates.definitionPathTemplate.match(definitionName)
      .definition;
  }

  /**
   * Return a fully-qualified dependency resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} dependency
   * @returns {string} Resource name string.
   */
  dependencyPath(project: string, location: string, dependency: string) {
    return this.pathTemplates.dependencyPathTemplate.render({
      project: project,
      location: location,
      dependency: dependency,
    });
  }

  /**
   * Parse the project from Dependency resource.
   *
   * @param {string} dependencyName
   *   A fully-qualified path representing Dependency resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromDependencyName(dependencyName: string) {
    return this.pathTemplates.dependencyPathTemplate.match(dependencyName)
      .project;
  }

  /**
   * Parse the location from Dependency resource.
   *
   * @param {string} dependencyName
   *   A fully-qualified path representing Dependency resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromDependencyName(dependencyName: string) {
    return this.pathTemplates.dependencyPathTemplate.match(dependencyName)
      .location;
  }

  /**
   * Parse the dependency from Dependency resource.
   *
   * @param {string} dependencyName
   *   A fully-qualified path representing Dependency resource.
   * @returns {string} A string representing the dependency.
   */
  matchDependencyFromDependencyName(dependencyName: string) {
    return this.pathTemplates.dependencyPathTemplate.match(dependencyName)
      .dependency;
  }

  /**
   * Return a fully-qualified deployment resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} deployment
   * @returns {string} Resource name string.
   */
  deploymentPath(project: string, location: string, deployment: string) {
    return this.pathTemplates.deploymentPathTemplate.render({
      project: project,
      location: location,
      deployment: deployment,
    });
  }

  /**
   * Parse the project from Deployment resource.
   *
   * @param {string} deploymentName
   *   A fully-qualified path representing Deployment resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromDeploymentName(deploymentName: string) {
    return this.pathTemplates.deploymentPathTemplate.match(deploymentName)
      .project;
  }

  /**
   * Parse the location from Deployment resource.
   *
   * @param {string} deploymentName
   *   A fully-qualified path representing Deployment resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromDeploymentName(deploymentName: string) {
    return this.pathTemplates.deploymentPathTemplate.match(deploymentName)
      .location;
  }

  /**
   * Parse the deployment from Deployment resource.
   *
   * @param {string} deploymentName
   *   A fully-qualified path representing Deployment resource.
   * @returns {string} A string representing the deployment.
   */
  matchDeploymentFromDeploymentName(deploymentName: string) {
    return this.pathTemplates.deploymentPathTemplate.match(deploymentName)
      .deployment;
  }

  /**
   * Return a fully-qualified externalApi resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} external_api
   * @returns {string} Resource name string.
   */
  externalApiPath(project: string, location: string, externalApi: string) {
    return this.pathTemplates.externalApiPathTemplate.render({
      project: project,
      location: location,
      external_api: externalApi,
    });
  }

  /**
   * Parse the project from ExternalApi resource.
   *
   * @param {string} externalApiName
   *   A fully-qualified path representing ExternalApi resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromExternalApiName(externalApiName: string) {
    return this.pathTemplates.externalApiPathTemplate.match(externalApiName)
      .project;
  }

  /**
   * Parse the location from ExternalApi resource.
   *
   * @param {string} externalApiName
   *   A fully-qualified path representing ExternalApi resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromExternalApiName(externalApiName: string) {
    return this.pathTemplates.externalApiPathTemplate.match(externalApiName)
      .location;
  }

  /**
   * Parse the external_api from ExternalApi resource.
   *
   * @param {string} externalApiName
   *   A fully-qualified path representing ExternalApi resource.
   * @returns {string} A string representing the external_api.
   */
  matchExternalApiFromExternalApiName(externalApiName: string) {
    return this.pathTemplates.externalApiPathTemplate.match(externalApiName)
      .external_api;
  }

  /**
   * Return a fully-qualified hostProjectRegistration resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} host_project_registration
   * @returns {string} Resource name string.
   */
  hostProjectRegistrationPath(
    project: string,
    location: string,
    hostProjectRegistration: string
  ) {
    return this.pathTemplates.hostProjectRegistrationPathTemplate.render({
      project: project,
      location: location,
      host_project_registration: hostProjectRegistration,
    });
  }

  /**
   * Parse the project from HostProjectRegistration resource.
   *
   * @param {string} hostProjectRegistrationName
   *   A fully-qualified path representing HostProjectRegistration resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromHostProjectRegistrationName(
    hostProjectRegistrationName: string
  ) {
    return this.pathTemplates.hostProjectRegistrationPathTemplate.match(
      hostProjectRegistrationName
    ).project;
  }

  /**
   * Parse the location from HostProjectRegistration resource.
   *
   * @param {string} hostProjectRegistrationName
   *   A fully-qualified path representing HostProjectRegistration resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromHostProjectRegistrationName(
    hostProjectRegistrationName: string
  ) {
    return this.pathTemplates.hostProjectRegistrationPathTemplate.match(
      hostProjectRegistrationName
    ).location;
  }

  /**
   * Parse the host_project_registration from HostProjectRegistration resource.
   *
   * @param {string} hostProjectRegistrationName
   *   A fully-qualified path representing HostProjectRegistration resource.
   * @returns {string} A string representing the host_project_registration.
   */
  matchHostProjectRegistrationFromHostProjectRegistrationName(
    hostProjectRegistrationName: string
  ) {
    return this.pathTemplates.hostProjectRegistrationPathTemplate.match(
      hostProjectRegistrationName
    ).host_project_registration;
  }

  /**
   * Return a fully-qualified plugin resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} plugin
   * @returns {string} Resource name string.
   */
  pluginPath(project: string, location: string, plugin: string) {
    return this.pathTemplates.pluginPathTemplate.render({
      project: project,
      location: location,
      plugin: plugin,
    });
  }

  /**
   * Parse the project from Plugin resource.
   *
   * @param {string} pluginName
   *   A fully-qualified path representing Plugin resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromPluginName(pluginName: string) {
    return this.pathTemplates.pluginPathTemplate.match(pluginName).project;
  }

  /**
   * Parse the location from Plugin resource.
   *
   * @param {string} pluginName
   *   A fully-qualified path representing Plugin resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromPluginName(pluginName: string) {
    return this.pathTemplates.pluginPathTemplate.match(pluginName).location;
  }

  /**
   * Parse the plugin from Plugin resource.
   *
   * @param {string} pluginName
   *   A fully-qualified path representing Plugin resource.
   * @returns {string} A string representing the plugin.
   */
  matchPluginFromPluginName(pluginName: string) {
    return this.pathTemplates.pluginPathTemplate.match(pluginName).plugin;
  }

  /**
   * Return a fully-qualified runtimeProjectAttachment resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} runtime_project_attachment
   * @returns {string} Resource name string.
   */
  runtimeProjectAttachmentPath(
    project: string,
    location: string,
    runtimeProjectAttachment: string
  ) {
    return this.pathTemplates.runtimeProjectAttachmentPathTemplate.render({
      project: project,
      location: location,
      runtime_project_attachment: runtimeProjectAttachment,
    });
  }

  /**
   * Parse the project from RuntimeProjectAttachment resource.
   *
   * @param {string} runtimeProjectAttachmentName
   *   A fully-qualified path representing RuntimeProjectAttachment resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromRuntimeProjectAttachmentName(
    runtimeProjectAttachmentName: string
  ) {
    return this.pathTemplates.runtimeProjectAttachmentPathTemplate.match(
      runtimeProjectAttachmentName
    ).project;
  }

  /**
   * Parse the location from RuntimeProjectAttachment resource.
   *
   * @param {string} runtimeProjectAttachmentName
   *   A fully-qualified path representing RuntimeProjectAttachment resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromRuntimeProjectAttachmentName(
    runtimeProjectAttachmentName: string
  ) {
    return this.pathTemplates.runtimeProjectAttachmentPathTemplate.match(
      runtimeProjectAttachmentName
    ).location;
  }

  /**
   * Parse the runtime_project_attachment from RuntimeProjectAttachment resource.
   *
   * @param {string} runtimeProjectAttachmentName
   *   A fully-qualified path representing RuntimeProjectAttachment resource.
   * @returns {string} A string representing the runtime_project_attachment.
   */
  matchRuntimeProjectAttachmentFromRuntimeProjectAttachmentName(
    runtimeProjectAttachmentName: string
  ) {
    return this.pathTemplates.runtimeProjectAttachmentPathTemplate.match(
      runtimeProjectAttachmentName
    ).runtime_project_attachment;
  }

  /**
   * Return a fully-qualified spec resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api
   * @param {string} version
   * @param {string} spec
   * @returns {string} Resource name string.
   */
  specPath(
    project: string,
    location: string,
    api: string,
    version: string,
    spec: string
  ) {
    return this.pathTemplates.specPathTemplate.render({
      project: project,
      location: location,
      api: api,
      version: version,
      spec: spec,
    });
  }

  /**
   * Parse the project from Spec resource.
   *
   * @param {string} specName
   *   A fully-qualified path representing Spec resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromSpecName(specName: string) {
    return this.pathTemplates.specPathTemplate.match(specName).project;
  }

  /**
   * Parse the location from Spec resource.
   *
   * @param {string} specName
   *   A fully-qualified path representing Spec resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromSpecName(specName: string) {
    return this.pathTemplates.specPathTemplate.match(specName).location;
  }

  /**
   * Parse the api from Spec resource.
   *
   * @param {string} specName
   *   A fully-qualified path representing Spec resource.
   * @returns {string} A string representing the api.
   */
  matchApiFromSpecName(specName: string) {
    return this.pathTemplates.specPathTemplate.match(specName).api;
  }

  /**
   * Parse the version from Spec resource.
   *
   * @param {string} specName
   *   A fully-qualified path representing Spec resource.
   * @returns {string} A string representing the version.
   */
  matchVersionFromSpecName(specName: string) {
    return this.pathTemplates.specPathTemplate.match(specName).version;
  }

  /**
   * Parse the spec from Spec resource.
   *
   * @param {string} specName
   *   A fully-qualified path representing Spec resource.
   * @returns {string} A string representing the spec.
   */
  matchSpecFromSpecName(specName: string) {
    return this.pathTemplates.specPathTemplate.match(specName).spec;
  }

  /**
   * Return a fully-qualified styleGuide resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} plugin
   * @returns {string} Resource name string.
   */
  styleGuidePath(project: string, location: string, plugin: string) {
    return this.pathTemplates.styleGuidePathTemplate.render({
      project: project,
      location: location,
      plugin: plugin,
    });
  }

  /**
   * Parse the project from StyleGuide resource.
   *
   * @param {string} styleGuideName
   *   A fully-qualified path representing StyleGuide resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromStyleGuideName(styleGuideName: string) {
    return this.pathTemplates.styleGuidePathTemplate.match(styleGuideName)
      .project;
  }

  /**
   * Parse the location from StyleGuide resource.
   *
   * @param {string} styleGuideName
   *   A fully-qualified path representing StyleGuide resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromStyleGuideName(styleGuideName: string) {
    return this.pathTemplates.styleGuidePathTemplate.match(styleGuideName)
      .location;
  }

  /**
   * Parse the plugin from StyleGuide resource.
   *
   * @param {string} styleGuideName
   *   A fully-qualified path representing StyleGuide resource.
   * @returns {string} A string representing the plugin.
   */
  matchPluginFromStyleGuideName(styleGuideName: string) {
    return this.pathTemplates.styleGuidePathTemplate.match(styleGuideName)
      .plugin;
  }

  /**
   * Return a fully-qualified version resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} api
   * @param {string} version
   * @returns {string} Resource name string.
   */
  versionPath(project: string, location: string, api: string, version: string) {
    return this.pathTemplates.versionPathTemplate.render({
      project: project,
      location: location,
      api: api,
      version: version,
    });
  }

  /**
   * Parse the project from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).project;
  }

  /**
   * Parse the location from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).location;
  }

  /**
   * Parse the api from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the api.
   */
  matchApiFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).api;
  }

  /**
   * Parse the version from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the version.
   */
  matchVersionFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).version;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    if (this.apiHubPluginStub && !this._terminated) {
      return this.apiHubPluginStub.then(stub => {
        this._log.info('ending gRPC channel');
        this._terminated = true;
        stub.close();
        this.locationsClient.close().catch(err => {
          throw err;
        });
      });
    }
    return Promise.resolve();
  }
}
