createTime: '2026-03-13T22:08:41.471207230Z'
description: Nightly build with node 18
gitFileSource:
  path: ci/cloudbuild_with_credentials.yaml
  repoType: GITHUB
  revision: refs/heads/main
  uri: https://github.com/googleapis/google-cloud-node
id: 566031e3-b29f-4979-a512-5513a6271cbf
name: core-samples-nightly-node-with-credentials
resourceName: projects/long-door-651/locations/global/triggers/566031e3-b29f-4979-a512-5513a6271cbf
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: https://github.com/googleapis/google-cloud-node
substitutions:
  _BUILD_TYPE: nightly
  _IS_CORE: 'true'
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
