createTime: '2026-03-13T22:08:38.885674430Z'
description: Continuous build with node gcnc
filename: ci/cloudbuild_with_credentials.yaml
github:
  name: google-cloud-node
  owner: googleapis
  push:
    branch: ^main$
id: a37cfd10-246f-4eed-8ca9-ee928e3a6289
name: core-samples-continuous-node-with-credentials
resourceName: projects/long-door-651/locations/global/triggers/a37cfd10-246f-4eed-8ca9-ee928e3a6289
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: continuous
  _IS_CORE: 'true'
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
