createTime: '2026-03-13T22:11:22.356625647Z'
description: Presubmit build with node 18
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 326669f8-0cd0-487c-a46f-716f34b7c473
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: packages-samples-presubmit-node
resourceName: projects/long-door-651/locations/global/triggers/326669f8-0cd0-487c-a46f-716f34b7c473
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
