createTime: '2026-03-13T22:10:56.695390313Z'
description: Continuous build with node 18
filename: ci/cloudbuild_with_credentials.yaml
github:
  name: google-cloud-node
  owner: googleapis
  push:
    branch: ^main$
id: 63adc177-3ed3-4729-9916-77a9c7c70da4
name: packages-samples-continuous-node-with-credentials
resourceName: projects/long-door-651/locations/global/triggers/63adc177-3ed3-4729-9916-77a9c7c70da4
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: continuous
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
