createTime: '2022-08-05T20:10:58.882437677Z'
description: Nightly build with node 14
gitFileSource:
  path: ci/cloudbuild_with_credentials.yaml
  repoType: GITHUB
  revision: refs/heads/main
  uri: https://github.com/googleapis/google-cloud-node
id: 25a89188-0ae6-4faf-9131-9b1e3c8b9720
name: samples-nightly-node14-with-credentials
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: https://github.com/googleapis/google-cloud-node
substitutions:
  _BUILD_TYPE: nightly
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
