createTime: '2022-12-20T00:38:41.361644100Z'
description: Presubmit build with node 14
filename: ci/cloudbuild_with_credentials.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 1686933b-458b-4b12-93bd-3c579c0a274d
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: samples-presubmit-node14-with-credentials
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
