createTime: '2022-08-05T20:10:51.866623226Z'
description: Presubmit build with node 14
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 209625ae-8ae4-4742-a175-4c1330cea557
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: samples-presubmit-node14
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
