createTime: '2022-06-22T20:37:14.244765001Z'
description: Presubmit build with node 18
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 28cdf776-546a-430e-b5ed-94cbbbcf493f
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: system-presubmit-node18
resourceName: projects/long-door-651/locations/global/triggers/28cdf776-546a-430e-b5ed-94cbbbcf493f
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: system
