createTime: '2022-12-22T19:23:12.819714241Z'
description: Presubmit build with node 18
filename: ci/cloudbuild_run_single_test.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 8d080c61-b90d-4d06-a5d2-417ac6166a60
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: unit-presubmit-node18
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _NODE_VERSION: '18'
  _TEST_TYPE: samples
