createTime: '2022-12-22T21:34:53.835122725Z'
description: Presubmit unit with node 16
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 182e003f-4636-4cc4-beda-811e6ad960f1
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: unit-presubmit-node16
resourceName: projects/long-door-651/locations/global/triggers/182e003f-4636-4cc4-beda-811e6ad960f1
serviceAccount: projects/-/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _NODE_VERSION: '16'
  _TEST_TYPE: units
