createTime: '2023-03-22T22:44:59.896784337Z'
description: Presubmit unit with node 12
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: 2a30298b-f453-459f-9f90-415527d051f2
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: unit-presubmit-node12
resourceName: projects/long-door-651/locations/global/triggers/2a30298b-f453-459f-9f90-415527d051f2
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _NODE_VERSION: '12'
  _TEST_TYPE: units
