# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

options:
  dynamic_substitutions: true

substitutions:
  _BUILD_TYPE: "presubmit"
  _TEST_TYPE: "system"
  _NODE_VERSION: "14"

logsBucket: 'gs://${_LOGS_BUCKET}/logs/google-cloud-node/${_BUILD_TYPE}/${COMMIT_SHA}/${TRIGGER_NAME}'
timeout: 7200s

steps:
  - name: 'gcr.io/kaniko-project/executor:v1.9.1'
    args: [
      '--log-format=text',
      '--context=dir:///workspace/testing',
      '--build-arg=NODE_VERSION=${_NODE_VERSION}',
      '--dockerfile=ci/Dockerfile',
      '--cache=true',
      '--destination=gcr.io/${PROJECT_ID}/google-cloud-node-${_NODE_VERSION}',
      '--push-retry=3',
      '--image-fs-extract-retry=3'
    ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --project=cloud-devrel-kokoro-resources --secret=long-door-651-kokoro-system-test-service-account --format='get(payload.data)'  | tr '_-' '/+' | base64 -d > /workspace/google_application_credentials.json" ]
  - name: gcr.io/${PROJECT_ID}/google-cloud-node-${_NODE_VERSION}
    id: "run-tests"
    timeout: 7200s
    entrypoint: "ci/run_conditional_tests.sh"
    env:
    - 'BUILD_TYPE=${_BUILD_TYPE}'
    - 'TEST_TYPE=${_TEST_TYPE}'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/google_application_credentials.json'
