permissions:
  contents: read

on:
  push:
    branches:
      - main
    # paths:
    #   - 'handwritten/storage/**'
  pull_request:
    # paths:
    #   - 'handwritten/storage/**'
name: conformance
jobs:
  conformance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 14
      - run: node --version
      - run: cd handwritten/storage && npm install
      - run: cd handwritten/storage && npm run conformance-test
