on:
  push:
    branches:
      - main
name: continuous
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          cache: true
      - run: node --version
      - run: pnpm install
      - run: pnpm --filter "{packages/**}" run test
        name: Run package/* unit tests
      - run: pnpm --filter "{containers/**}" run test
        name: Run containers/* unit tests
      - run: ci/run_conditional_tests.sh
        name: Run core, handwritten, and .github/scripts tests
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: units
