on:
  push:
    branches:
      - main
name: continuous
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ^6.24.1
      - run: node --version
      - run: ci/run_conditional_tests.sh
        name: Run unit tests
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: units
