permissions:
  contents: read

on:
  push:
    branches:
      - main
name: continuous
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 22, 24, 26]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4
      - run: node --version
      - run: ci/run_conditional_tests.sh
        name: Run unit tests
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: units
