on:
  push:
    branches:
      - main
name: continuous
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.32.2
      - run: node --version
      - run: ci/run_conditional_tests.sh
        name: Check lint
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: lint
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ^6.24.1
      - run: node --version
      - run: ci/run_conditional_tests.sh
        name: Run unit tests
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: units
