permissions:
  contents: read

on:
  schedule:
    - cron: '0 12 * * TUE'
  workflow_dispatch:
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4

      # Install all deps, including dev dependencies.
      - run: cd handwritten/bigquery && pnpm install --filter .
      # Generate types
      - run: cd handwritten/bigquery && pnpm run types
      # Fix formatting
      - run: cd handwritten/bigquery && pnpm run fix
      # Submit pull request
      - uses: googleapis/code-suggester@f9fef85aa02459e30e62526abe950341cbbd768b # v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: googleapis
          upstream_repo: google-cloud-node
          description: 'Automated pull-request to keep BigQuery Discovery types up-to-date.'
          title: 'chore: update types from Discovery'
          message: 'chore: update types from Discovery'
          branch: update-discovery-patch
          git_dir: 'handwritten/bigquery'
          fork: true
          force: true
