on:
  schedule:
    - cron: '0 12 * * TUE'
  workflow_dispatch:
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 16
      # Install all deps, including dev dependencies.
      - run: cd handwritten/bigquery && npm install
      # Generate types
      - run: cd handwritten/bigquery && npm run types
      # Fix formatting
      - run: cd handwritten/bigquery && npm run fix
      # Submit pull request
      - uses: googleapis/code-suggester@v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: googleapis
          upstream_repo: google-cloud-node
          description: 'Automated pull-request to keep BigQuery Discovery types up-to-date.'
          title: 'chore: update types from Discovery'
          message: 'chore: update types from Discovery'
          branch: update-discovery-patch
          git_dir: 'handwritten/bigquery'
          fork: true
          force: true
