name: invalid_link
on:
  issues:
    types: [opened, edited]

jobs:
  close:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/close-unresponsive.js')
            await script({github, context})