permissions:
  contents: read

on:
  pull_request:
name: presubmit
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      shard-matrix: ${{ steps.set-matrix.outputs.shard_matrix }}
      shard-total: ${{ steps.set-matrix.outputs.shard_total }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - id: set-matrix
        uses: ./.github/actions/calculate-shard-matrix
  units:
    needs: setup
    name: units (Node ${{ matrix.node-version }}, Shard ${{ matrix.shard-index }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]
        shard-index: ${{ fromJSON(needs.setup.outputs.shard-matrix) }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - uses: ./.github/actions/run-unit-tests
        with:
          node-version: ${{ matrix.node-version }}
          shard-total: ${{ needs.setup.outputs.shard-total }}
          shard-index: ${{ matrix.shard-index }}
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Use Node.js 24
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
      - run: npm install
      - run: node ./bin/linter.mjs --strict
        name: Run monorepo linter
        env:
          GIT_DIFF_ARG: "HEAD^1...HEAD"

  # Consolidate shards into jobs representing aggregate status to simplify branch protection requirements
  units-status:
    name: units (${{ matrix.node-version }})
    needs: units
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Check shard status
        uses: ./.github/actions/check-shard-status
        with:
          node-version: ${{ matrix.node-version }}
