name: Publish logging-winston package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: handwritten/logging-winston

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@guestbutler'
          cache: npm
          cache-dependency-path: handwritten/logging-winston/

      - run: |
          pwd
          ls
          npm ci

      - run: npm test

      - name: Set package version from release tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi

          VERSION="${VERSION#v}"

          npm version "$VERSION" --no-git-tag-version

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}