permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'handwritten/storage/**'
  pull_request:
    paths:
      - 'handwritten/storage/**'
name: storage-conformance
jobs:
  conformance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
      - run: node --version
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm --filter ...{handwritten/storage} run --if-present compile
      - run: cd handwritten/storage && pnpm run conformance-test
