permissions:
  contents: read

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-api-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 18
      - run: npm install
      - run: npm run generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: googleapis/code-suggester@f9fef85aa02459e30e62526abe950341cbbd768b # v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          force: true
          upstream_owner: googleapis
          upstream_repo: google-cloud-node
          description: 'Update the list of available APIs in the README.'
          title: 'docs: update the list of available APIs'
          message: 'docs: update the list of available APIs'
          branch: update-api-list
          git_dir: '.'
