permissions:
  contents: read

on:
  pull_request:
name: presubmit-windows
jobs:
  units:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18, 22, 24, 26]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 300
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4
      - name: Install Workspace Dependencies (Frozen Lockfile)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm -r run compile
      - run: node --version
      - run: bash ci/run_conditional_tests.sh
        name: Run windows unit tests
        shell: bash
        env:
          BUILD_TYPE: presubmit
          TEST_TYPE: units
